export interface Area {
  id: string
  label: string
  color: string
}

export const AREAS: Area[] = [
  { id: 'atividade-parlamentar', label: 'Atividade Parlamentar', color: '#94a3b8' },
  { id: 'seguranca',             label: 'Segurança Pública',     color: '#1d4ed8' },
  { id: 'saude',                 label: 'Saúde',                 color: '#ef4444' },
  { id: 'educacao',              label: 'Educação',              color: '#3b82f6' },
  { id: 'justica-direito',       label: 'Justiça & Direito',     color: '#7c3aed' },
  { id: 'meio-ambiente',         label: 'Meio Ambiente',         color: '#22c55e' },
  { id: 'agropecuaria',          label: 'Agropecuária',          color: '#84cc16' },
  { id: 'trabalho',              label: 'Trabalho & Emprego',    color: '#eab308' },
  { id: 'infraestrutura',        label: 'Infraestrutura',        color: '#f97316' },
  { id: 'cultura-esporte',       label: 'Cultura, Esporte & Turismo', color: '#f43f5e' },
  { id: 'tecnologia',            label: 'Tecnologia & Inovação', color: '#06b6d4' },
  { id: 'direitos-humanos',      label: 'Direitos Humanos',      color: '#ec4899' },
  { id: 'economia-privada',      label: 'Economia Privada',      color: '#8b5cf6' },
  { id: 'economia-publica',      label: 'Economia Pública',      color: '#6366f1' },
  { id: 'adm-publica',           label: 'Administração Pública', color: '#64748b' },
  { id: 'outros',                label: 'Outros',                color: '#9ca3af' },
]

// Ordem importa: primeiro match ganha.
// "Atividade Parlamentar" vem primeiro para evitar que "frente parlamentar de saúde" vá para Saúde.
const KEYWORDS: [string, string[]][] = [
  ['atividade-parlamentar', [
    'frente parlamentar',
    'sessão solene',
    'regime de urgência',
    'tramitação sob o regime',
    'dispensa do interstício',
    'requer a realização de sessão',
    'requer o registro da frente',
    'requer a criação da frente',
    'requer a instalação da frente',
    'inclusão de membro',
    'inclusão de assinatura',
    'co-autoria',
    'requer inclusão das assinaturas',
    'recurso contra a tramitação conclusiva',
    'recurso contra a apreciação terminativa',
    'ofício',
  ]],
  ['seguranca', [
    'segurança pública',
    'segurança nacional',
    'polícia',
    'policial',
    'violência doméstica',
    'violência urbana',
    'crime organizado',
    'crime violento',
    'imputabilidade penal',
    'pena privativa',
    'penitenciária',
    'presídio',
    'prisão',
    'delegacia',
    'bombeiro',
    'defesa civil',
    'investigação criminal',
    'código de processo penal',
    'arma de fogo',
    'porte de arma',
    'armamento',
    'tráfico de drogas',
    'tráfico de pessoas',
    'homicídio',
    'latrocínio',
    'feminicídio',
  ]],
  ['saude', [
    'saúde',
    'médico',
    'médica',
    'hospital',
    'paciente',
    'doença',
    'tratamento de',
    'vacina',
    'enfermagem',
    'farmácia',
    'farmacêutico',
    'sanitário',
    'pandemia',
    'medicament',
    'clínica',
    'nutrição',
    'saúde mental',
    'oncolog',
    'plano de saúde',
    'assistência médica',
    'assistência farmacêutica',
    'sistema único de saúde',
    ' sus ',
    'vigilância sanitária',
    'anvisa',
    'epidemia',
    'transtorno',
    'deficiência auditiva',
    'deficiência visual',
  ]],
  ['educacao', [
    'educação',
    'escola',
    'ensino',
    'aluno',
    'professor',
    'universidade',
    'faculdade',
    'pedagógic',
    'creche',
    'alfabetização',
    'colégio',
    'estudante',
    'acadêmic',
    'graduação',
    'pesquisa científica',
    'enade',
    'bolsa de estudo',
    'bolsa família',
    'prouni',
    'fies',
    'base nacional comum curricular',
  ]],
  ['justica-direito', [
    'judiciário',
    'poder judiciário',
    'tribunal',
    'magistrado',
    'juiz',
    'vara ',
    'processo judicial',
    'código de processo civil',
    'código penal',
    'código civil',
    'conselho nacional de justiça',
    'cnj',
    'stf',
    'stj',
    'defensoria pública',
    'ministério público',
    'advocacia',
    'execução penal',
  ]],
  ['meio-ambiente', [
    'meio ambiente',
    'floresta',
    'ambiental',
    'preservação ambiental',
    'preservação da natureza',
    'sustentável',
    'reciclagem',
    'resíduo sólido',
    'carbono',
    'emissão de gases',
    'fauna',
    'flora',
    'bioma',
    'amazônia',
    'desmatamento',
    'poluição',
    'biodiversidade',
    'unidade de conservação',
    'área de proteção ambiental',
    'licença ambiental',
    'proteção animal',
    'maus-tratos a animais',
    'bem-estar animal',
    'causa animal',
  ]],
  ['agropecuaria', [
    'agricultura',
    'agropecuária',
    'produtor rural',
    'pecuária',
    'agrário',
    'assentamento rural',
    'reforma agrária',
    'soja',
    'gado',
    'bovino',
    'irrigação',
    'orgânico',
    'agrotóxico',
    'pesca',
    'aquicultura',
    'silvicultura',
    'cooperativa agrícola',
    'crédito rural',
    'seguro rural',
    'pronaf',
    'agricultura familiar',
    'vitivinicultura',
  ]],
  ['trabalho', [
    'trabalhador',
    'trabalhista',
    'emprego',
    'empregad',
    'salário mínimo',
    'remuneração',
    'clt',
    'sindicato',
    'seguro desemprego',
    'home office',
    'teletrabalho',
    'terceirização',
    'jornada de trabalho',
    'carteira de trabalho',
    'aposentadoria',
    'piso salarial',
    'fgts',
    'fundo de garantia',
    'benefício trabalhista',
    'acidente de trabalho',
    'medicina do trabalho',
    'insalubridade',
    'periculosidade',
  ]],
  ['infraestrutura', [
    'rodovia',
    'estrada',
    'ferrovia',
    'porto ',
    'aeroporto',
    'saneamento',
    'habitação',
    'moradia',
    'mobilidade urbana',
    'transporte público',
    'energia elétrica',
    'telecomunicação',
    'trânsito',
    'veículo',
    'condutor',
    'habilitação',
    ' cnh ',
    'combustível',
    'petróleo',
    'gás natural',
    'etanol',
    'gasolina',
    'energia renovável',
    'energia solar',
    'energia eólica',
    'pré-sal',
    'hídric',
    'abastecimento de água',
    'esgoto',
    'pavimentação',
  ]],
  ['cultura-esporte', [
    'cultura',
    'turismo',
    'esporte',
    'atleta',
    'olímpic',
    'paraolímpic',
    'futebol',
    'competição esportiva',
    'patrimônio cultural',
    'patrimônio histórico',
    'festival',
    'arte ',
    'música',
    'cinema',
    'teatro',
    'folclor',
    'dança',
    'literatura',
    'museu',
    'biblioteca',
    'carnaval',
    'manifestação cultural',
  ]],
  ['tecnologia', [
    'tecnologia da informação',
    'inteligência artificial',
    'dados pessoais',
    'lgpd',
    'software',
    'aplicativo',
    'plataforma digital',
    'governo digital',
    'dados abertos',
    'cibersegurança',
    'blockchain',
    'inovação tecnológica',
    'transformação digital',
    'startups',
    'ecossistema de inovação',
  ]],
  ['direitos-humanos', [
    'direitos humanos',
    'criança e adolescente',
    'estatuto da criança',
    'violência contra a mulher',
    'lei maria da penha',
    'proteção da mulher',
    'pessoa idosa',
    'estatuto do idoso',
    'pessoa com deficiência',
    'estatuto da pessoa',
    'racial',
    'quilombola',
    'indígena',
    'lgbtq',
    'lgbti',
    'discriminação',
    'igualdade racial',
    'acessibilidade',
    'inclusão social',
    'vulnerabilidade social',
    'assistência social',
    'população em situação de rua',
    'refugiado',
    'migrante',
    'protetor',
  ]],
  ['economia-privada', [
    'investimento privado',
    'subsídio',
    'incentivo fiscal',
    'concessão',
    'privatização',
    'parceria público-privada',
    ' ppp ',
    'empreendedorismo',
    'microempresa',
    'empresa de pequeno porte',
    ' mei ',
    'simples nacional',
    'exportação',
    'importação',
    'comércio exterior',
    'mercado de capitais',
    'mercado financeiro',
    'crédito privado',
    'financiamento privado',
    'banco ',
    'financeiro',
    'fundo de investimento',
    'taxa de juros',
    'spread bancário',
    'correspondente bancário',
  ]],
  ['economia-publica', [
    'imposto',
    'tributo',
    'tributação',
    'orçamento',
    'receita federal',
    'tesouro nacional',
    'gasto público',
    'déficit fiscal',
    'previdência social',
    'inss',
    'contribuição previdenciária',
    'dívida pública',
    'icms',
    'irpf',
    'cofins',
    'iss ',
    'pis ',
    'benefício previdenciário',
    'benefício de prestação continuada',
    'bpc ',
    'loas',
    'pensão por morte',
    'benefício social',
    'precatório',
    'emenda orçamentária',
  ]],
  ['adm-publica', [
    'servidor público',
    'servidores públicos',
    'licitação',
    'contrato administrativo',
    'transparência pública',
    'lei de responsabilidade fiscal',
    'controle interno',
    'autarquia',
    'administração pública',
    'gestão pública',
    'política pública',
    'programa nacional',
    'programa federal',
    'política nacional de',
    'cadastro nacional',
    'sistema nacional',
    'conselho nacional',
    'fundo nacional',
  ]],
]

export function classificarProposicao(ementa: string): string {
  const lower = ementa.toLowerCase()
  for (const [areaId, keywords] of KEYWORDS) {
    if (keywords.some((kw) => lower.includes(kw))) return areaId
  }
  return 'outros'
}

export function getArea(id: string): Area {
  return AREAS.find((a) => a.id === id) ?? AREAS[AREAS.length - 1]
}
